# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:06
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bio', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(default='2016-03-03')),
                ('display_pic', models.ImageField(blank=True, upload_to=accounts.models.upload_location)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
