# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='related_name', to='accounts.UserProfile'),
        ),
    ]
