# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:53
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160603_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_pic',
            field=models.ImageField(upload_to=accounts.models.upload_location),
        ),
    ]
