# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160603_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.UserProfile'),
        ),
    ]
