# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 06:39
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160630_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location),
        ),
    ]
