# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
