# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_auto_20160530_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
