# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirps', '0003_auto_20160601_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='likes',
        ),
        migrations.AddField(
            model_name='chirp',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
