# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirps', '0004_auto_20160605_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='origin_chirp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ori_chirp_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chirp',
            name='rechirp_status',
            field=models.BooleanField(default=False),
        ),
    ]
