# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0005_auto_20160606_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chirps.chirp'),
        ),
    ]
