# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0006_chirp_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
