# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0007_auto_20160630_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chirps.Chirp'),
        ),
    ]
